post http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyIiwiaWQiOiI1ZGJjYTI2ZWMzN2ZlMjE3M2FkYmMzMmQiLCJpYXQiOjE1NzI2NDk2MDZ9.n_AcGqnJ2QGUMgf-16_-nr2dse-bVRc02J6ys8TAVkw
Content-Type: application/json

{
    "title": "Hel1l1o",
    "author": "Gibson",
    "url": "www.gibsonhan.com",
    "likes": 100
}